#!/bin/bash
#SBATCH -J kmeans_job
#SBATCH -o kmeans.out
#SBATCH -e kmeans.err
#SBATCH -t 0-00:30
#SBATCH --constraint=cuda-7.5

#SBATCH –p gpu.test
#SBATCH -N 2
#SBATCH -n 2
#SBATCH --ntasks-per-socket=1
#SBATCH --gres=gpu:2
#SBATCH --mem-per-cpu=4000

module load python/2.7.12
module load cuda/7.5.18
module load gcc/5.4.0 
module load openmpi/1.10.3
source activate pycuda

git pull
srun -n $SLURM_NTASKS --mpi=pmi2 python run.py
