#!/bin/bash
#SBATCH -J kmeans
#SBATCH -o kmeans.out
#SBATCH -e kmeans.err
#SBATCH -p gpu
#SBATCH -n 1
#SBATCH --gres=gpu:2
#SBATCH -t 0-00:30
#SBATCH --mem-per-cpu=500
#SBATCH --constraint=cuda-7.5

git fetch
git pull

module load python/2.7.11-fasrc01
module load cuda/7.5-fasrc02
module load gcc/4.8.2-fasrc01 openmpi/1.10.2-fasrc01
source activate pycuda

srun -n $SLURM_NTASKS --mpi=pmi2 python kmeans.py
